name: Enforce Prerelease

on:
  release:
    types: [created]

jobs:
  enforce-prerelease:
    # 新規作成された latest release のみを対象にする
    if: github.event.release.prerelease == false && github.event.release.draft == false
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Delete invalid release
        id: delete_release
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const release_id = context.payload.release.id;
            const release_tag = context.payload.release.tag_name;
            const release_name = context.payload.release.name;
            
            console.log(`Deleting invalid release ${release_id}`);
            
            // Store release info for notification
            core.setOutput('release_tag', release_tag);
            core.setOutput('release_name', release_name);
            
            // Delete the release
            await github.rest.repos.deleteRelease({
              owner,
              repo,
              release_id
            });
            
            console.log('Release deleted successfully');
            
      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: ${{ secrets.TEST_NOTIFY_SLACK_CHANNEL }}
          payload: |
            {
              "attachments": [
                {
                  "color": "#FFC107",
                  "blocks": [
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "*⚠️ 警告: Prerelease を経由しないリリース*"
                      }
                    },
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "リリース `${{ steps.delete_release.outputs.release_name }}` が prerelease を経由せずに作成されました。\n自動的に削除しました。"
                      }
                    },
                    {
                      "type": "context",
                      "elements": [
                        {
                          "type": "mrkdwn",
                          "text": "削除されたタグ: `${{ steps.delete_release.outputs.release_tag }}`"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|actions>"
                        }
                      ]
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}