name: Force Prerelease Flow

on:
  release:
    types: [created]

jobs:
  convert-to-draft:
    # 新規作成された latest release のみを対象にする
    if: github.event.release.prerelease == false && github.event.release.draft == false
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Convert to draft
        id: convert_release
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const release_id = context.payload.release.id;
            const release_tag = context.payload.release.tag_name;
            const release_name = context.payload.release.name;
            
            console.log(`Converting release ${release_id} to draft`);
            
            // Store release info for notification
            core.setOutput('release_tag', release_tag);
            core.setOutput('release_name', release_name);
            
            // Update release to draft
            await github.rest.repos.updateRelease({
              owner,
              repo,
              release_id,
              draft: true
            });
            
            console.log('Release converted to draft successfully');
            
            // Get the updated release URL
            const updatedRelease = await github.rest.repos.getRelease({
              owner,
              repo,
              release_id
            });
            
            // Set output for next step
            core.setOutput('release_url', updatedRelease.data.html_url);
            
      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: ${{ secrets.TEST_NOTIFY_SLACK_CHANNEL }}
          payload: |
            {
              "attachments": [
                {
                  "color": "#FFC107",
                  "blocks": [
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "*⚠️ 警告: Prerelease を経由しないリリース*"
                      }
                    },
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "リリース `${{ steps.convert_release.outputs.release_name }}` が prerelease を経由せずに作成されました。\n自動的に draft に変換しました。"
                      }
                    },
                    {
                      "type": "context",
                      "elements": [
                        {
                          "type": "mrkdwn",
                          "text": "<${{ steps.convert_release.outputs.release_url }}|リリースを確認>"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|actions>"
                        }
                      ]
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}